### ISSUE TITLE
Milestone 1 readiness list

### ISSUE THREAD

**Issue by MeerKatDev** [eigerco/uniffi-zcash-lib#1]
Per each language, the user should be able to:

- [ ] Generate documentation
  - we need to modify the UniFFI library for this, a work already underway, which we hope to release in the coming two weeks
- [x] Run demo tests in docker
- [x] Run demo tests in native environment
  - at the moment `cargo test` runs all of them together
- [x] Create a Pull Request and see it running through the pipeline with all green
- [x] Understand how to make/compile libraries locally (`cargo build` is enough for now)
- [x] Understand how the team conducts the development work 
  - we still need to establish an actual dev workflow, but we can run the basic commands `cargo build && cargo test`
- [x] Understand what are the code conventions in place
- [x] Understand how the code can be licensed
