### ISSUE TITLE
Milestone 2 readiness list

### ISSUE THREAD

**Issue by MeerKatDev** [eigerco/uniffi-zcash-lib#2]
- [x] Create a new private key
  - `from_seed` generates a new private key from the account id + seed
- [x] Derive a new spending key (SK) from a private key
  - we could not find a way to derive a SK from a PK, also upon further inspection it was just easier to build a full USK from seed and from an account, with `unified_sk_from_seed`
- [x] Derive an incoming viewing (IVK) key from a (Unified) spending key
  - at the moment it is done indirectly with `unified_fvk_from_usk` + `ivk_from_ufvk`
- [x] Derive a full viewing key (FVK) from a (Unified) spending key
  - in brief: `unified_fvk_from_usk`
- [x] Derive an outgoing viewing key (OVK) from a (Unified) spending key
  - at the moment it is done indirectly with `unified_fvk_from_usk` + `ovk_from_ufvk`

From last week:
 - [x] Documentation generation - we think we arrived to a good point in which a string from the UDL docs are propagated to the different platforms. We're going to improve on it over the coming weeks. [Here](https://github.com/eigerco/uniffi-rs) our fork which we're using as dependency for this project.

At the moment we're internally testing out different approaches, i.e. whether instead of the freely dangling functions use an object/interface approach. Naming is still subject to change. Tests are a bit messy but we're working on making them more ergonomic.

From the next week, the development process will be more transparent.
